version: "3.8"

services:

  #Zookeeper
  zookeeper:
    image: zookeeper
    ports:
      - "2181"

  #Kafka
  kafka:
    image: bitnami/kafka:3.5.1-debian-11-r6
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  #Postgres
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  #Scorpio
  scorpio:
    image: scorpiobroker/all-in-one-runner:java-kafka-4.1.10
    ports:
      - "9090:9090"
    environment:
      DBHOST: postgres
      BUSHOST: kafka
    depends_on:
      - postgres
      - kafka

  broker-adapter:
    container_name: broker-adapter
    hostname: broker-adapter
    image: in2kizuna/broker-adapter:v1.0.0-SNAPSHOT
    environment:
      - "BROKER_EXTERNALDOMAIN=https://<example.com>/orion-ld"
      - "BROKER_INTERNALDOMAIN=http://scorpio:9090"
      - "BROKER-ADAPTER_OPENAPI_URL=http://localhost:8080"
    ports:
      - "8083:8080"
    depends_on:
      - scorpio

  # Blockchain Connector
  blockchain-connector:
    hostname: blockchain-connector
    container_name: blockchain-connector
    image: in2kizuna/blockchain-connector:v1.0.0-SNAPSHOT
    environment:
      - "SPRING_R2DBC_URL=r2dbc:postgresql://mkt-postgres:5432/mktdb"
      - "FLYWAY_URL=jdbc:postgresql://mkt-postgres:5432/mktdb"
      - "ORGANIZATION_ID=VATES-00869735"
    ports:
      - "8081:8080"
    volumes:
      - ./marketplace1-config.yml:/src/main/resources/external-config.yml
    depends_on:
      - broker-adapter
      - mkt1-dlt-adapter
      - mkt-postgres

  mkt-postgres:
    hostname: mkt-postgres
    container_name: mkt-postgres
    image: postgres:11
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mktdb

  mkt1-dlt-adapter:
    container_name: mkt1-dlt-adapter
    image: aleniet/dlt-adapter:1.1
    environment:
      - "PRIVATE_KEY=0xe2afef2c880b138d741995ba56936e389b0b5dd2943e21e4363cc70d81c89346"
    ports:
      - "8082:8080"

   # Marketplace 2 Instance
#  mkt2-blockchain-connector:
#    container_name: mkt2-blockchain-connector
#    image: blockchain-connector:latest
#    environment:
#      - "DATABASE_URL=r2dbc:postgresql://mkt2-postgres:5432/mktdb"
#      - "FLYWAY_URL=jdbc:postgresql://mkt2-postgres:5432/mktdb"
#      - "ORGANIZATION_ID=VATFR-00900867"
#    ports:
#      - "8084:8080"
#    volumes:
#      - ./marketplace2-config.yml:/src/main/resources/external-config.yml
#    links:
#      - mkt2-broker-adapter
#      - mkt2-dlt-adapter
#      - mkt2-postgres
#    networks:
#      - local_network
#
#  mkt2-postgres:
#    container_name: mkt2-postgres
#    image: postgres:11
#    ports:
#      - "5434:5432"
#    environment:
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=mktdb
#    hostname: mkt2-postgres
#    networks:
#      - local_network
#
#  mkt2-dlt-adapter:
#    container_name: mkt2-dlt-adapter
#    image: aleniet/dlt-adapter:1.1
#    environment:
#      - "PRIVATE_KEY=0xe2afef2c880b138d741995ba56936e389b0b5dd2943e21e4363cc70d81c89346"
#    ports:
#      - "8085:8080"
#    networks:
#      - local_network
#
#  mkt2-broker-adapter:
#    container_name: mkt2-broker-adapter
#    image: in2kizuna/broker-adapter:v1.0.0-SNAPSHOT
#    ports:
#      - "8086:8080"
#    volumes:
#      - ./marketplace2-config.yml:/src/main/resources/external-config.yml
#    links:
#      - mkt2-context-broker
#    networks:
#      - local_network
#
#  mkt2-context-broker:
#    container_name: mkt2-context-broker
#    image: fiware/orion-ld:latest
#    restart: always
#    command: "-dbhost mkt2-mongo -port 1026"
#    ports:
#      - "1028:1026"
#    links:
#      - mkt2-mongo
#    networks:
#      - local_network
#
#  mkt2-mongo:
#    container_name: mkt2-mongo
#    image: mongo:4.4
#    command: "--nojournal"
#    volumes:
#      - mkt2_data:/data/db
#      - mkt2_db_config:/data/configdb
#    networks:
#      - local_network

networks:
  local_network:
    driver: bridge

volumes:
  postgres-data:
  mkt1_data:
  mkt1_db_config:
  mkt1_mysql:
  mkt2_data:
  mkt2_db_config:
  mkt2_mysql:
