# Orion-LD Interface Configuration
orion-ld-if:
  orion-ld:
    domain: http://orion-ld:1026
    path:
      entities: /ngsi-ld/v1/entities
      subscriptions: /ngsi-ld/v1/subscriptions
  api:
    domain: http://orionld-adapter:8080
    path:
      subscription: /api/v1/subscribe
      entities: /api/v1/entities
      update: /api/v1/update
      publish: /api/v1/publish