# Blockchain Connector Configuration
blockchain-connector:
  openapi:
    url: http://mkt1-blockchain-connector:8080

# DLT Adapter Configuration
dlt-adapter:
  domain: http://mkt1-dlt-adapter:8080

# Blockchain Configuration
blockchain:
  rpcAddress: https://red-t.alastria.io/v0/9461d9f4292b41230527d57ee90652a6
  userEthereumAddress: "0xb794f5ea0ba39494ce839613fffba74279579268"
  subscription:
    active: false
    notificationEndpoint: http://mkt1-blockchain-connector:8080/notifications/dlt
    entityTypes: >
      ProductOffering

# Broker Adapter Configuration
broker-adapter:
  domain: http://mkt1-broker-adapter:8080 # blockchain-connector configuration
  openapi:
    url: http://localhost:8080 # broker-adapter configuration

# Context Broker Configuration
broker:
  externalDomain: https://<example.com>/orion-ld
  internalDomain: http://mkt1-context-broker:1026

# NGSI Subscription Configuration
ngsi-subscription:
  notificationEndpoint: http://mkt1-blockchain-connector:8080/notifications/broker
  entityTypes: >
    ProductOffering
